{
 "title": "Prometheus Home Dashboard",
 "description": "Prometheus Home Dashboard",
 "tags": [
  "prometheus",
  "linux"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source:", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "10.10.2.2:9100, 10.10.2.4:9100, 10.10.2.6:9100"
   },
   {
    "name": "disk",
    "query": "/dev/sda, /dev/sdb, /dev/sdc, /dev/sdd"
   },
   { "name": "g_ports", "label": "Gateway:", "query": "eth0, eth2" },
   { "name": "gateway", "label": "Gateway IP", "query": "10.10.1.1" },
   { "name": "w_radio", "label": "WiFi:", "query": "rai1, rai2" },
   { "name": "unifiap1", "label": "Unifi AP 1 IP", "query": "10.10.1.21" },
   { "name": "webservice1", "query": "https://webmin.yourdomain.com" },
   { "name": "webservice2", "query": "http://10.10.2.2:8201" },
   { "name": "webservice3", "query": "http://10.10.2.4:8181" }
  ]
 },
 "panels": [
  { "title": "Host: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=~\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Disk Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Disk Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_device_smart_healthy{ instance=~\"10.10.2.2:9100\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{ instance=~\"10.10.2.2:9100\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_cycle_count_raw_value{ instance=~\"10.10.2.2:9100\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power On Hours",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_on_hours_raw_value{ instance=~\"10.10.2.2:9100\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Portal Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{job=\"blackbox\",instance=~\"$webservice1\"}"
    }
   ]
  },
  {
   "title": "SSL Connection",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{job=\"blackbox\",instance=~\"$webservice1\"}"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=\"blackbox\",instance=~\"$webservice1\"} - time()"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=\"blackbox\",instance=~\"$webservice1\"})"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{job=\"blackbox\",instance=~\"$webservice1\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 15, "y": 22 } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 18, "y": 22 } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 } },
  {
   "title": "Webmin Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\",instance=~\"$webservice1\"}"
    }
   ]
  },
  {
   "title": "Portainer Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\",instance=~\"$webservice2\"}"
    }
   ]
  },
  {
   "title": "Nginx Proxy Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\",instance=~\"$webservice3\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 } },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 } },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 } },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 } },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 } },
  { "title": "Gateway: $g_ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "g_ports" },
  {
   "title": "Tx (Recent)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Recent)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Transmit / Receive",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[5m])",
     "legendFormat": "Tx"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[5m])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Adm. Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$gateway\"}/100"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sysUpTime{instance=\"$gateway\"} - on(instance) ifLastChange{instance=\"$gateway\",ifName=\"$g_ports\"}) / 100"
    }
   ]
  },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  {
   "title": "Maximum TU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  { "title": "WiFi: $w_radio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "w_radio" },
  {
   "title": "Tx (Recent)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Recent)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Drop Rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(unifiVapTxDropped{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) + delta(unifiVapTxErrors{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range])) / delta(unifiVapTxPackets{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) * 100",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Drop Rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(unifiVapRxDropped{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) + delta(unifiVapRxErrors{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range])) / delta(unifiVapRxPackets{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) * 100",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Retry Rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(delta(unifiVapTxRetries{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) / delta(unifiVapTxPackets{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) * 100, 0)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Adm. Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$unifiap1\",ifName=\"$w_radio\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$unifiap1\"}/100"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sysUpTime{instance=\"$unifiap1\"} - on(instance) ifLastChange{instance=\"$unifiap1\",ifName=\"$w_radio\"}) / 100"
    }
   ]
  },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$unifiap1\",ifName=\"$w_radio\"}"
    }
   ]
  },
  {
   "title": "WiFi Channel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifiVapChannel{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}"
    }
   ]
  },
  {
   "title": "Maximum TU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$unifiap1\",ifName=\"$w_radio\"}"
    }
   ]
  },
  { "title": "Home Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 } }
 ]
}